version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.96
    working_directory:  ~/hugo
    environment: 
      HUGO_BUILD_DIR: ~/hugo/public
    steps:
      - checkout
      - run: git submodule sync && git submodule update --init
      - run: sudo apt update && sudo apt install python3-pip python3-dev
      - run: pip3 install awscli
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      # - run: |
      #     htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html \
      #     --empty-alt-ignore --disable-external
      - deploy:
          name: deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws s3 sync $HUGO_BUILD_DIR \
              s3://zackwang.me --delete
            else
              echo "Not master branch, dry run only"
            fi